name: Daily Test

on:
  schedule:
    - cron: '0 7 * * *'

env:
  USE_GH_PAGES_SITE: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install node_modules
        run: npm i
      - name: Build
        run: npm run build
      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      - name: Run Playwright tests
        run: npm test
