name: Website Build And Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install node_modules
        run: npm i
      - name: Build
        run: npm run build
      - name: Run Playwright tests
        run: npm test
      - name: Artifact build output
        uses: actions/upload-artifact@main
        with:
          name: website-build
          path: dist
          retention-days: "1"
          
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages    
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v3
        with:
          name: website-build
          path: website-build
      - name: Create github_pages.tar artifact
        run: |
          cd ./website-build
          tar -cvf ../github_pages.tar ./
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: "./github_pages.tar"
          retention-days: "1"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
