name: Website Build And Publish

on:
  push:
    branches: [ main ]

env:
  USE_GH_PAGES_SITE: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install node_modules
        run: npm i
      - name: Build
        run: npm run build
      - name: Install Playwright Dependencies
        run: npx playwright install-deps
      - name: Run Playwright tests
        run: npm test
      - name: Create github_pages.tar artifact
        run: |
          cd ./dist
          tar -cvf ../github_pages.tar ./
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: "./github_pages.tar"
          retention-days: "1"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
