name: Website Build And Publish

on:
  push:
    branches: [ main ]

jobs:
  Pages:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install node_modules
        run: npm i
      - name: Build
        run: npm run build
      - name: List files in the repository
        run: ls ${{ github.workspace }}