name: Website Build And Publish

on:
  push:
    branches: [ main ]

jobs:
  Pages:

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install node_modules
        run: npm i
      - name: Build
        run: npm run build
      - name: Create github_pages.tar artifact
        run: tar -czvf ./github_pages.tar ./dist
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: "./github_pages.tar"
          retention-days: "1"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1